/**
 * 🎯 BANCO DE PALAVRAS PARA ALFABETIZAÇÃO
 *
 * Organizado por dificuldade e categoria
 * Total: 550+ palavras em 18 categorias
 * Categorias: Animais, Comidas, Objetos, Natureza, Família, Lugares,
 *             Pessoas, Ações, Cores, Transportes, Fantasia, Esportes,
 *             Profissões, Corpo, Música, Emoções, Conceitos, Números
 * Atualizado: 2025-11-14
 */

const WORD_BANK = {
  // ==========================================
  // NÍVEL FÁCIL - Palavras de 3 letras
  // ==========================================
  easy: {
    animals: [
      { text: "BOI", emoji: "🐂" },
      { text: "CÃO", emoji: "🐕" },
      { text: "BOA", emoji: "🐍" },
      { text: "RÃ", emoji: "🐸" },
      { text: "BUG", emoji: "🐛" },
    ],
    nature: [
      { text: "SOL", emoji: "☀️" },
      { text: "LUA", emoji: "🌙" },
      { text: "MAR", emoji: "🌊" },
      { text: "CÉU", emoji: "☁️" },
      { text: "AR", emoji: "💨" },
      { text: "FÉ", emoji: "🙏" },
      { text: "LUZ", emoji: "💡" },
      { text: "FIM", emoji: "🏁" },
    ],
    family: [
      { text: "PAI", emoji: "👨" },
      { text: "MÃE", emoji: "👩" },
      { text: "AVÓ", emoji: "👵" },
      { text: "AVÔ", emoji: "👴" },
      { text: "TIO", emoji: "👨‍🦱" },
      { text: "TIA", emoji: "👩‍🦰" },
      { text: "VOV", emoji: "👵" },
    ],
    objects: [
      { text: "PÉ", emoji: "🦶" },
      { text: "MÃO", emoji: "✋" },
      { text: "REI", emoji: "👑" },
      { text: "DIA", emoji: "📅" },
      { text: "NOZ", emoji: "🌰" },
      { text: "UVA", emoji: "🍇" },
      { text: "LÃ", emoji: "🧶" },
      { text: "BAÚ", emoji: "📦" },
      { text: "ASA", emoji: "🦅" },
    ],
    food: [
      { text: "PÃO", emoji: "🍞" },
      { text: "OVO", emoji: "🥚" },
      { text: "CHÁ", emoji: "🍵" },
      { text: "MEL", emoji: "🍯" },
      { text: "SAL", emoji: "🧂" },
      { text: "UVA", emoji: "🍇" },
      { text: "CHU", emoji: "🍭" },
    ],
    others: [
      { text: "RUA", emoji: "🛣️" },
      { text: "BOA", emoji: "👍" },
      { text: "SIM", emoji: "✅" },
      { text: "NÃO", emoji: "❌" },
      { text: "VER", emoji: "👁️" },
      { text: "LER", emoji: "📖" },
      { text: "VOZ", emoji: "🗣️" },
      { text: "PAZ", emoji: "☮️" },
      { text: "DEZ", emoji: "🔟" },
      { text: "COR", emoji: "🎨" },
      { text: "DOR", emoji: "😣" },
      { text: "FAZ", emoji: "✨" },
      { text: "VAI", emoji: "➡️" },
      { text: "VEM", emoji: "⬅️" },
      { text: "TEM", emoji: "✋" },
      { text: "DÁ", emoji: "🤲" },
      { text: "VIU", emoji: "👀" },
      { text: "FOI", emoji: "🚶" },
    ],
    sports: [
      { text: "GOL", emoji: "⚽" },
      { text: "BOL", emoji: "🏀" },
      { text: "RED", emoji: "🏐" },
    ],
    professions: [
      { text: "REI", emoji: "👑" },
      { text: "VET", emoji: "👨‍⚕️" },
      { text: "DJ", emoji: "🎧" },
    ],
    body: [
      { text: "PÉ", emoji: "🦶" },
      { text: "MÃO", emoji: "✋" },
      { text: "BOC", emoji: "👄" },
      { text: "DED", emoji: "👆" },
    ],
    music: [
      { text: "SOM", emoji: "🔊" },
      { text: "CD", emoji: "💿" },
      { text: "RAP", emoji: "🎤" },
    ],
    numbers: [
      { text: "UM", emoji: "1️⃣" },
      { text: "DOI", emoji: "2️⃣" },
      { text: "DEZ", emoji: "🔟" },
      { text: "CEM", emoji: "💯" },
      { text: "MIL", emoji: "🔢" },
    ]
  },

  // ==========================================
  // NÍVEL MÉDIO - Palavras de 4-5 letras
  // ==========================================
  medium: {
    animals: [
      { text: "GATO", emoji: "🐱" },
      { text: "RATO", emoji: "🐭" },
      { text: "PATO", emoji: "🦆" },
      { text: "SAPO", emoji: "🐸" },
      { text: "URSO", emoji: "🐻" },
      { text: "LOBO", emoji: "🐺" },
      { text: "FOCA", emoji: "🦭" },
      { text: "LEÃO", emoji: "🦁" },
      { text: "COBRA", emoji: "🐍" },
      { text: "MACACO", emoji: "🐵" },
      { text: "PORCO", emoji: "🐷" },
      { text: "VACA", emoji: "🐄" },
      { text: "PEIXE", emoji: "🐟" },
      { text: "ZEBRA", emoji: "🦓" },
      { text: "PANDA", emoji: "🐼" },
      { text: "TIGRE", emoji: "🐯" },
      { text: "CORUJA", emoji: "🦉" },
      { text: "PÁSSARO", emoji: "🐦" },
      { text: "FORMIGA", emoji: "🐜" },
      { text: "COELHO", emoji: "🐰" },
      { text: "RAPOSA", emoji: "🦊" },
      { text: "VEADO", emoji: "🦌" },
      { text: "CAVALO", emoji: "🐴" },
      { text: "OVELHA", emoji: "🐑" },
      { text: "CABRA", emoji: "🐐" },
      { text: "CAMELO", emoji: "🐫" },
      { text: "BALEIA", emoji: "🐋" },
      { text: "GOLFINHO", emoji: "🐬" },
      { text: "POLVO", emoji: "🐙" },
      { text: "TUBARÃO", emoji: "🦈" },
      { text: "PINGUIM", emoji: "🐧" },
      { text: "FLAMINGO", emoji: "🦩" },
      { text: "ÁGUIA", emoji: "🦅" },
      { text: "PAPAGAIO", emoji: "🦜" },
      { text: "BEIJA-FLOR", emoji: "🐦" },
      { text: "GALINHA", emoji: "🐔" },
      { text: "PINTINHO", emoji: "🐤" },
      { text: "PERU", emoji: "🦃" },
      { text: "PAVÃO", emoji: "🦚" },
      { text: "CISNE", emoji: "🦢" },
      { text: "GANSO", emoji: "🦆" },
      { text: "CORVO", emoji: "🐦‍⬛" },
      { text: "MORCEGO", emoji: "🦇" },
      { text: "ESQUILO", emoji: "🐿️" },
      { text: "OURIÇO", emoji: "🦔" },
      { text: "LONTRA", emoji: "🦦" },
      { text: "GAMBÁ", emoji: "🦨" },
      { text: "TEXUGO", emoji: "🦡" },
      { text: "ARANHA", emoji: "🕷️" },
      { text: "ABELHA", emoji: "🐝" },
      { text: "JOANINHA", emoji: "🐞" },
      { text: "BORBOLETA", emoji: "🦋" },
      { text: "MOSCA", emoji: "🪰" },
      { text: "MOSQUITO", emoji: "🦟" },
      { text: "GRILO", emoji: "🦗" },
      { text: "CARACOL", emoji: "🐌" },
      { text: "LAGOSTA", emoji: "🦞" },
      { text: "CARANGUEJO", emoji: "🦀" },
      { text: "CAMARÃO", emoji: "🦐" },
    ],
    food: [
      { text: "BOLO", emoji: "🎂" },
      { text: "PIZZA", emoji: "🍕" },
      { text: "SOPA", emoji: "🍲" },
      { text: "SUCO", emoji: "🧃" },
      { text: "LEITE", emoji: "🥛" },
      { text: "QUEIJO", emoji: "🧀" },
      { text: "MAÇÃ", emoji: "🍎" },
      { text: "BANANA", emoji: "🍌" },
      { text: "LARANJA", emoji: "🍊" },
      { text: "MELANCIA", emoji: "🍉" },
      { text: "MORANGO", emoji: "🍓" },
      { text: "CEREJA", emoji: "🍒" },
      { text: "ABACAXI", emoji: "🍍" },
      { text: "CENOURA", emoji: "🥕" },
      { text: "TOMATE", emoji: "🍅" },
      { text: "BATATA", emoji: "🥔" },
      { text: "MILHO", emoji: "🌽" },
      { text: "ARROZ", emoji: "🍚" },
      { text: "FEIJÃO", emoji: "🫘" },
      { text: "PÊRA", emoji: "🍐" },
      { text: "PÊSSEGO", emoji: "🍑" },
      { text: "MELÃO", emoji: "🍈" },
      { text: "LIMÃO", emoji: "🍋" },
      { text: "COCO", emoji: "🥥" },
      { text: "KIWI", emoji: "🥝" },
      { text: "MANGA", emoji: "🥭" },
      { text: "MAMÃO", emoji: "🫐" },
      { text: "UVAS", emoji: "🍇" },
      { text: "ABACATE", emoji: "🥑" },
      { text: "BRÓCOLIS", emoji: "🥦" },
      { text: "ALFACE", emoji: "🥬" },
      { text: "PEPINO", emoji: "🥒" },
      { text: "PIMENTÃO", emoji: "🫑" },
      { text: "BERINJELA", emoji: "🍆" },
      { text: "COGUMELO", emoji: "🍄" },
      { text: "AMENDOIM", emoji: "🥜" },
      { text: "CASTANHA", emoji: "🌰" },
      { text: "PINHA", emoji: "🍁" },
      { text: "HAMBÚRGUER", emoji: "🍔" },
      { text: "CACHORRO-QUENTE", emoji: "🌭" },
      { text: "SANDUÍCHE", emoji: "🥪" },
      { text: "TACO", emoji: "🌮" },
      { text: "BURRITO", emoji: "🌯" },
      { text: "MACARRÃO", emoji: "🍝" },
      { text: "ESPAGUETE", emoji: "🍝" },
      { text: "LASANHA", emoji: "🍝" },
      { text: "CARNE", emoji: "🥩" },
      { text: "FRANGO", emoji: "🍗" },
      { text: "BACON", emoji: "🥓" },
      { text: "SALSICHA", emoji: "🌭" },
      { text: "CAMARÃO", emoji: "🦐" },
      { text: "OMELETE", emoji: "🍳" },
      { text: "PANQUECA", emoji: "🥞" },
      { text: "WAFFLE", emoji: "🧇" },
      { text: "BISCOITO", emoji: "🍪" },
      { text: "TORTA", emoji: "🥧" },
      { text: "CUPCAKE", emoji: "🧁" },
      { text: "DONUTS", emoji: "🍩" },
      { text: "SORVETE", emoji: "🍨" },
      { text: "PICOLÉ", emoji: "🍦" },
      { text: "CHOCOLATE", emoji: "🍫" },
      { text: "BOMBOM", emoji: "🍬" },
      { text: "BALA", emoji: "🍭" },
      { text: "PIPOCA", emoji: "🍿" },
      { text: "ÁGUA", emoji: "💧" },
      { text: "CAFÉ", emoji: "☕" },
      { text: "CHOCO", emoji: "🍫" },
      { text: "VITAMINA", emoji: "🥤" },
      { text: "IOGURTE", emoji: "🥛" },
      { text: "MANTEIGA", emoji: "🧈" },
    ],
    objects: [
      { text: "BOLA", emoji: "⚽" },
      { text: "MESA", emoji: "🪑" },
      { text: "MALA", emoji: "🧳" },
      { text: "DADO", emoji: "🎲" },
      { text: "FOGO", emoji: "🔥" },
      { text: "VELA", emoji: "🕯️" },
      { text: "CAMA", emoji: "🛏️" },
      { text: "PORTA", emoji: "🚪" },
      { text: "JANELA", emoji: "🪟" },
      { text: "CADEIRA", emoji: "🪑" },
      { text: "LIVRO", emoji: "📚" },
      { text: "LÁPIS", emoji: "✏️" },
      { text: "PAPEL", emoji: "📄" },
      { text: "BOLSA", emoji: "👜" },
      { text: "RELÓGIO", emoji: "⏰" },
      { text: "CHAVE", emoji: "🔑" },
      { text: "PENTE", emoji: "🪮" },
      { text: "ESCOVA", emoji: "🪥" },
      { text: "SABÃO", emoji: "🧼" },
      { text: "ESPELHO", emoji: "🪞" },
      { text: "SOFÁ", emoji: "🛋️" },
      { text: "TAPETE", emoji: "🧺" },
      { text: "CORTINA", emoji: "🪟" },
      { text: "LÂMPADA", emoji: "💡" },
      { text: "QUADRO", emoji: "🖼️" },
      { text: "FOTO", emoji: "📷" },
      { text: "TESOURA", emoji: "✂️" },
      { text: "COLA", emoji: "🧴" },
      { text: "CANETA", emoji: "🖊️" },
      { text: "BORRACHA", emoji: "📝" },
      { text: "RÉGUA", emoji: "📏" },
      { text: "MOCHILA", emoji: "🎒" },
      { text: "ESTOJO", emoji: "📚" },
      { text: "CADERNO", emoji: "📔" },
      { text: "AGENDA", emoji: "📅" },
      { text: "CALENDÁRIO", emoji: "📆" },
      { text: "TELEFONE", emoji: "📱" },
      { text: "COMPUTADOR", emoji: "💻" },
      { text: "TECLADO", emoji: "⌨️" },
      { text: "MOUSE", emoji: "🖱️" },
      { text: "FONE", emoji: "🎧" },
      { text: "MICROFONE", emoji: "🎤" },
      { text: "CÂMERA", emoji: "📸" },
      { text: "BATERIA", emoji: "🔋" },
      { text: "LANTERNA", emoji: "🔦" },
      { text: "GUARDA-CHUVA", emoji: "☂️" },
      { text: "MOCHILA", emoji: "🎒" },
      { text: "CHAPÉU", emoji: "🎩" },
      { text: "BONÉ", emoji: "🧢" },
      { text: "ÓCULOS", emoji: "👓" },
      { text: "LUVA", emoji: "🧤" },
      { text: "CACHECOL", emoji: "🧣" },
      { text: "SAPATO", emoji: "👟" },
      { text: "SANDÁLIA", emoji: "🩴" },
      { text: "BOTA", emoji: "🥾" },
      { text: "MEIA", emoji: "🧦" },
      { text: "CAMISA", emoji: "👕" },
      { text: "CALÇA", emoji: "👖" },
      { text: "VESTIDO", emoji: "👗" },
      { text: "SAIA", emoji: "👘" },
      { text: "JAQUETA", emoji: "🧥" },
      { text: "PIJAMA", emoji: "🩱" },
      { text: "TOALHA", emoji: "🧻" },
      { text: "COBERTOR", emoji: "🛏️" },
      { text: "TRAVESSEIRO", emoji: "🛏️" },
      { text: "LENÇOL", emoji: "🛏️" },
      { text: "PRATO", emoji: "🍽️" },
      { text: "COPO", emoji: "🥤" },
      { text: "XÍCARA", emoji: "☕" },
      { text: "COLHER", emoji: "🥄" },
      { text: "GARFO", emoji: "🍴" },
      { text: "FACA", emoji: "🔪" },
      { text: "PANELA", emoji: "🍲" },
      { text: "FRIGIDEIRA", emoji: "🍳" },
      { text: "CHALEIRA", emoji: "🫖" },
      { text: "BALDE", emoji: "🪣" },
      { text: "VASSOURA", emoji: "🧹" },
      { text: "PÁ", emoji: "🧹" },
      { text: "RODO", emoji: "🧹" },
      { text: "ESPONJA", emoji: "🧽" },
      { text: "PANO", emoji: "🧻" },
    ],
    nature: [
      { text: "FLOR", emoji: "🌸" },
      { text: "ÁRVORE", emoji: "🌳" },
      { text: "FOLHA", emoji: "🍂" },
      { text: "NUVEM", emoji: "☁️" },
      { text: "CHUVA", emoji: "🌧️" },
      { text: "VENTO", emoji: "💨" },
      { text: "RAIO", emoji: "⚡" },
      { text: "NEVE", emoji: "❄️" },
      { text: "ARCO-ÍRIS", emoji: "🌈" },
      { text: "MONTANHA", emoji: "⛰️" },
      { text: "RIO", emoji: "🏞️" },
      { text: "LAGO", emoji: "🏞️" },
      { text: "PRAIA", emoji: "🏖️" },
      { text: "OCEANO", emoji: "🌊" },
      { text: "DESERTO", emoji: "🏜️" },
      { text: "FLORESTA", emoji: "🌲" },
    ],
    places: [
      { text: "CASA", emoji: "🏠" },
      { text: "ESCOLA", emoji: "🏫" },
      { text: "PARQUE", emoji: "🏞️" },
      { text: "PRÉDIO", emoji: "🏢" },
      { text: "LOJA", emoji: "🏪" },
      { text: "HOSPITAL", emoji: "🏥" },
      { text: "IGREJA", emoji: "⛪" },
      { text: "JARDIM", emoji: "🌺" },
      { text: "FAZENDA", emoji: "🌾" },
      { text: "CIDADE", emoji: "🏙️" },
    ],
    people: [
      { text: "BEBÊ", emoji: "👶" },
      { text: "CRIANÇA", emoji: "🧒" },
      { text: "MENINO", emoji: "👦" },
      { text: "MENINA", emoji: "👧" },
      { text: "AMIGO", emoji: "👫" },
      { text: "IRMÃO", emoji: "👦" },
      { text: "IRMÃ", emoji: "👧" },
      { text: "PRIMO", emoji: "👦" },
      { text: "PRIMA", emoji: "👧" },
    ],
    actions: [
      { text: "PULAR", emoji: "🦘" },
      { text: "CORRER", emoji: "🏃" },
      { text: "ANDAR", emoji: "🚶" },
      { text: "DORMIR", emoji: "😴" },
      { text: "COMER", emoji: "🍽️" },
      { text: "BEBER", emoji: "🥤" },
      { text: "BRINCAR", emoji: "🎮" },
      { text: "ESTUDAR", emoji: "📚" },
      { text: "CANTAR", emoji: "🎤" },
      { text: "DANÇAR", emoji: "💃" },
    ],
    colors: [
      { text: "AZUL", emoji: "🔵" },
      { text: "VERDE", emoji: "🟢" },
      { text: "VERMELHO", emoji: "🔴" },
      { text: "AMARELO", emoji: "🟡" },
      { text: "ROSA", emoji: "🌸" },
      { text: "ROXO", emoji: "🟣" },
      { text: "LARANJA", emoji: "🟠" },
      { text: "BRANCO", emoji: "⚪" },
      { text: "PRETO", emoji: "⚫" },
      { text: "CINZA", emoji: "⚪" },
    ],
    transport: [
      { text: "CARRO", emoji: "🚗" },
      { text: "ÔNIBUS", emoji: "🚌" },
      { text: "TREM", emoji: "🚂" },
      { text: "AVIÃO", emoji: "✈️" },
      { text: "BARCO", emoji: "⛵" },
      { text: "BICICLETA", emoji: "🚲" },
      { text: "MOTO", emoji: "🏍️" },
      { text: "CAMINHÃO", emoji: "🚚" },
    ],
    fantasy: [
      { text: "FADA", emoji: "🧚‍♀️" },
      { text: "BRUXA", emoji: "🧙‍♀️" },
      { text: "DRAGÃO", emoji: "🐉" },
      { text: "UNICÓRNIO", emoji: "🦄" },
      { text: "SEREIA", emoji: "🧜‍♀️" },
      { text: "FANTASMA", emoji: "👻" },
      { text: "ROBÔ", emoji: "🤖" },
      { text: "ALIEN", emoji: "👽" },
    ],
    sports: [
      { text: "FUTEBOL", emoji: "⚽" },
      { text: "BASQUETE", emoji: "🏀" },
      { text: "VÔLEI", emoji: "🏐" },
      { text: "TÊNIS", emoji: "🎾" },
      { text: "NATAÇÃO", emoji: "🏊" },
      { text: "CORRIDA", emoji: "🏃" },
      { text: "PULO", emoji: "🦘" },
      { text: "GINÁSTICA", emoji: "🤸" },
      { text: "DANÇA", emoji: "💃" },
      { text: "SKATE", emoji: "🛹" },
      { text: "BICICLETA", emoji: "🚴" },
      { text: "KARATÊ", emoji: "🥋" },
      { text: "JUDÔ", emoji: "🥋" },
      { text: "BOXE", emoji: "🥊" },
      { text: "ESCALADA", emoji: "🧗" },
      { text: "SURFE", emoji: "🏄" },
      { text: "ESQUI", emoji: "⛷️" },
      { text: "PATINS", emoji: "⛸️" },
      { text: "GOLFE", emoji: "⛳" },
      { text: "BEISEBOL", emoji: "⚾" },
    ],
    professions: [
      { text: "MÉDICO", emoji: "👨‍⚕️" },
      { text: "PROFESSOR", emoji: "👨‍🏫" },
      { text: "DENTISTA", emoji: "🦷" },
      { text: "ENFERMEIRO", emoji: "👩‍⚕️" },
      { text: "POLICIAL", emoji: "👮" },
      { text: "BOMBEIRO", emoji: "🚒" },
      { text: "COZINHEIRO", emoji: "👨‍🍳" },
      { text: "PADEIRO", emoji: "🥖" },
      { text: "ARTISTA", emoji: "🎨" },
      { text: "MÚSICO", emoji: "🎵" },
      { text: "CANTOR", emoji: "🎤" },
      { text: "DANÇARINO", emoji: "💃" },
      { text: "PILOTO", emoji: "✈️" },
      { text: "MOTORISTA", emoji: "🚗" },
      { text: "FAZENDEIRO", emoji: "🌾" },
      { text: "JARDINEIRO", emoji: "🌱" },
      { text: "PEDREIRO", emoji: "🧱" },
      { text: "PINTOR", emoji: "🎨" },
      { text: "VETERINÁRIO", emoji: "🐕" },
      { text: "CIENTISTA", emoji: "🔬" },
    ],
    body: [
      { text: "CABEÇA", emoji: "👤" },
      { text: "OLHO", emoji: "👁️" },
      { text: "NARIZ", emoji: "👃" },
      { text: "BOCA", emoji: "👄" },
      { text: "ORELHA", emoji: "👂" },
      { text: "DENTE", emoji: "🦷" },
      { text: "LÍNGUA", emoji: "👅" },
      { text: "PESCOÇO", emoji: "🧣" },
      { text: "OMBRO", emoji: "🫱" },
      { text: "BRAÇO", emoji: "💪" },
      { text: "COTOVELO", emoji: "🫱" },
      { text: "PULSO", emoji: "⌚" },
      { text: "BARRIGA", emoji: "🤰" },
      { text: "COSTA", emoji: "🧍" },
      { text: "PERNA", emoji: "🦵" },
      { text: "JOELHO", emoji: "🦵" },
      { text: "TORNOZELO", emoji: "🦶" },
      { text: "DEDO", emoji: "👆" },
      { text: "UNHA", emoji: "💅" },
      { text: "CORAÇÃO", emoji: "❤️" },
    ],
    music: [
      { text: "VIOLÃO", emoji: "🎸" },
      { text: "PIANO", emoji: "🎹" },
      { text: "BATERIA", emoji: "🥁" },
      { text: "FLAUTA", emoji: "🎶" },
      { text: "VIOLINO", emoji: "🎻" },
      { text: "TROMPETE", emoji: "🎺" },
      { text: "SAXOFONE", emoji: "🎷" },
      { text: "HARPA", emoji: "🪕" },
      { text: "TAMBOR", emoji: "🥁" },
      { text: "MICROFONE", emoji: "🎤" },
      { text: "NOTA", emoji: "🎵" },
      { text: "MÚSICA", emoji: "🎶" },
      { text: "CANÇÃO", emoji: "🎵" },
      { text: "MELODIA", emoji: "🎶" },
    ],
    numbers: [
      { text: "ZERO", emoji: "0️⃣" },
      { text: "UM", emoji: "1️⃣" },
      { text: "DOIS", emoji: "2️⃣" },
      { text: "TRÊS", emoji: "3️⃣" },
      { text: "QUATRO", emoji: "4️⃣" },
      { text: "CINCO", emoji: "5️⃣" },
      { text: "SEIS", emoji: "6️⃣" },
      { text: "SETE", emoji: "7️⃣" },
      { text: "OITO", emoji: "8️⃣" },
      { text: "NOVE", emoji: "9️⃣" },
      { text: "DEZ", emoji: "🔟" },
      { text: "ONZE", emoji: "🔢" },
      { text: "DOZE", emoji: "🔢" },
      { text: "VINTE", emoji: "🔢" },
      { text: "TRINTA", emoji: "🔢" },
      { text: "CEM", emoji: "💯" },
    ]
  },

  // ==========================================
  // NÍVEL DIFÍCIL - Palavras complexas
  // ==========================================
  hard: {
    animals: [
      { text: "ELEFANTE", emoji: "🐘" },
      { text: "GIRAFA", emoji: "🦒" },
      { text: "RINOCERONTE", emoji: "🦏" },
      { text: "HIPOPÓTAMO", emoji: "🦛" },
      { text: "CROCODILO", emoji: "🐊" },
      { text: "BORBOLETA", emoji: "🦋" },
      { text: "JOANINHA", emoji: "🐞" },
      { text: "CARACOL", emoji: "🐌" },
      { text: "TARTARUGA", emoji: "🐢" },
      { text: "DINOSSAURO", emoji: "🦕" },
    ],
    nature: [
      { text: "RELÂMPAGO", emoji: "⚡" },
      { text: "TROVÃO", emoji: "🌩️" },
      { text: "TERREMOTO", emoji: "🌍" },
      { text: "VULCÃO", emoji: "🌋" },
      { text: "CACHOEIRA", emoji: "🏞️" },
      { text: "ARCO-ÍRIS", emoji: "🌈" },
      { text: "TEMPESTADE", emoji: "⛈️" },
    ],
    objects: [
      { text: "COMPUTADOR", emoji: "💻" },
      { text: "TELEFONE", emoji: "📱" },
      { text: "TELEVISÃO", emoji: "📺" },
      { text: "GELADEIRA", emoji: "🧊" },
      { text: "FOGÃO", emoji: "🍳" },
      { text: "MICROONDAS", emoji: "🍲" },
      { text: "BRINQUEDO", emoji: "🧸" },
      { text: "PRESENTE", emoji: "🎁" },
      { text: "INSTRUMENTO", emoji: "🎸" },
      { text: "TELESCÓPIO", emoji: "🔭" },
      { text: "MICROSCÓPIO", emoji: "🔬" },
    ],
    emotions: [
      { text: "FELICIDADE", emoji: "😊" },
      { text: "ALEGRIA", emoji: "😄" },
      { text: "TRISTEZA", emoji: "😢" },
      { text: "SAUDADE", emoji: "💭" },
      { text: "AMOR", emoji: "❤️" },
      { text: "AMIZADE", emoji: "🤝" },
      { text: "CORAGEM", emoji: "💪" },
      { text: "ESPERANÇA", emoji: "🌟" },
    ],
    concepts: [
      { text: "ESTRELA", emoji: "⭐" },
      { text: "CORAÇÃO", emoji: "❤️" },
      { text: "FAMÍLIA", emoji: "👨‍👩‍👧‍👦" },
      { text: "EDUCAÇÃO", emoji: "🎓" },
      { text: "SABEDORIA", emoji: "🦉" },
      { text: "IMAGINAÇÃO", emoji: "💭" },
      { text: "AVENTURA", emoji: "🗺️" },
      { text: "DESCOBERTA", emoji: "🔍" },
    ],
    sports: [
      { text: "ATLETISMO", emoji: "🏃" },
      { text: "NATAÇÃO", emoji: "🏊" },
      { text: "GINÁSTICA", emoji: "🤸" },
      { text: "JUDÔ", emoji: "🥋" },
      { text: "KARATÊ", emoji: "🥋" },
      { text: "CICLISMO", emoji: "🚴" },
      { text: "SKATEBOARD", emoji: "🛹" },
      { text: "ESCALADA", emoji: "🧗" },
      { text: "CAMPEONATO", emoji: "🏆" },
      { text: "MEDALHA", emoji: "🏅" },
    ],
    professions: [
      { text: "ENGENHEIRO", emoji: "👷" },
      { text: "ARQUITETO", emoji: "📐" },
      { text: "CIENTISTA", emoji: "🔬" },
      { text: "ASTRONAUTA", emoji: "👨‍🚀" },
      { text: "BOMBEIRO", emoji: "🚒" },
      { text: "VETERINÁRIO", emoji: "👨‍⚕️" },
      { text: "COZINHEIRO", emoji: "👨‍🍳" },
      { text: "MÚSICO", emoji: "🎵" },
      { text: "PINTOR", emoji: "🎨" },
      { text: "PROGRAMADOR", emoji: "💻" },
    ],
    body: [
      { text: "CORAÇÃO", emoji: "❤️" },
      { text: "CÉREBRO", emoji: "🧠" },
      { text: "PULMÃO", emoji: "🫁" },
      { text: "ESTÔMAGO", emoji: "🫃" },
      { text: "ESQUELETO", emoji: "💀" },
      { text: "JOELHO", emoji: "🦵" },
      { text: "COTOVELO", emoji: "💪" },
      { text: "TORNOZELO", emoji: "🦶" },
      { text: "SOBRANCELHA", emoji: "👁️" },
      { text: "UNHA", emoji: "💅" },
    ],
    music: [
      { text: "ORQUESTRA", emoji: "🎻" },
      { text: "SINFONIA", emoji: "🎼" },
      { text: "MELODIA", emoji: "🎵" },
      { text: "HARMONIA", emoji: "🎶" },
      { text: "SAXOFONE", emoji: "🎷" },
      { text: "TROMPETE", emoji: "🎺" },
      { text: "CLARINETE", emoji: "🎷" },
      { text: "VIOLONCELO", emoji: "🎻" },
      { text: "TECLADO", emoji: "🎹" },
      { text: "MICROFONE", emoji: "🎤" },
    ],
    numbers: [
      { text: "QUINZE", emoji: "🔢" },
      { text: "DEZESSEIS", emoji: "🔢" },
      { text: "DEZESSETE", emoji: "🔢" },
      { text: "DEZOITO", emoji: "🔢" },
      { text: "DEZENOVE", emoji: "🔢" },
      { text: "QUARENTA", emoji: "🔢" },
      { text: "CINQUENTA", emoji: "🔢" },
      { text: "SESSENTA", emoji: "🔢" },
      { text: "SETENTA", emoji: "🔢" },
      { text: "OITENTA", emoji: "🔢" },
      { text: "NOVENTA", emoji: "🔢" },
      { text: "DUZENTOS", emoji: "🔢" },
      { text: "TREZENTOS", emoji: "🔢" },
      { text: "QUINHENTOS", emoji: "🔢" },
      { text: "MIL", emoji: "🔢" },
      { text: "MILHÃO", emoji: "🔢" },
    ]
  }
};

/**
 * Retorna todas as palavras de um nível, mescladas de todas as categorias
 */
function getAllWordsForLevel(level) {
  const levelWords = WORD_BANK[level];
  const allWords = [];

  for (const category in levelWords) {
    allWords.push(...levelWords[category]);
  }

  return allWords;
}

/**
 * Retorna palavras de uma categoria específica
 */
function getWordsByCategory(level, category) {
  return WORD_BANK[level][category] || [];
}

/**
 * Retorna uma palavra aleatória do nível
 */
function getRandomWord(level, excludeWords = []) {
  const allWords = getAllWordsForLevel(level);
  const availableWords = allWords.filter(w => !excludeWords.includes(w.text));

  if (availableWords.length === 0) {
    return null;
  }

  return availableWords[Math.floor(Math.random() * availableWords.length)];
}

/**
 * Retorna estatísticas do banco de palavras
 */
function getWordBankStats() {
  const stats = {};

  for (const level in WORD_BANK) {
    stats[level] = {
      total: getAllWordsForLevel(level).length,
      categories: Object.keys(WORD_BANK[level]).length
    };
  }

  return stats;
}

// Exporta para uso global
if (typeof window !== 'undefined') {
  window.WORD_BANK = WORD_BANK;
  window.getAllWordsForLevel = getAllWordsForLevel;
  window.getWordsByCategory = getWordsByCategory;
  window.getRandomWord = getRandomWord;
  window.getWordBankStats = getWordBankStats;
}
